<?php
$userName = $this->escape($this->user["user_name"]);
?>
<br /><br />
<div id="view-content">
	<p>Sửa thông tin người dùng</b></p>
	<form method="post" action="<?php echo $this->url([
			'controller'=>'user',
			'action'=>'update',
			'id'=>$this->user['id']
	]); ?>">
		<?php echo $this->formText('user_name', $this->user['user_name'])?>
		<input type="text" value='<?php echo $this->user['user_name'];?>' name="user_name"><br>
		<input type="text" value='<?php echo $this->user['user_pass'];?>' name="user_pass"><br>
		<input type="text" value='<?php echo $this->user['user_phone'];?>' name="user_phone"><br>
		<input type="text" value='<?php echo $this->user['user_address'];?>' name="user_address"><br>
		<input type="text" value='<?php echo $this->user['user_email'];?>' name="user_email"><br>
		<input type="text" value='<?php echo $this->user['user_age'];?>' name="user_age"><br>
		<input type="submit" value="Sửa bản ghi" name="btn_edit">
	</form>
	
</div>