<?php
$this->title = "My Albums";
$this->headTitle($this->title);

?>
<p><a href="<?php 
		echo $this->url(array('controller'=>'user',
 							  'action'=>'add'));
?>">Add new album</a></p>
<table>
<tr>
 <th>Title</th>
 <th>Artist</th>
 <th>&nbsp;</th>
</tr>
<?php
		//var_dump($this->user);
		//$album=$this->user;
 foreach($this->user as $album) : ?>
<tr>
 <td><?php echo $this->escape($album['user_name']);?></td>
 <td><?php echo $this->escape($album['user_email']);?></td>
 <td>
 <a href="<?php echo $this->url(array('controller'=>'user',
 'action'=>'edit', 'id'=>$album['id']));?>">Edit</a>
 Page 12 of
18
 <a href="<?php echo $this->url(array('controller'=>'user',
 'action'=>'delete', 'id'=>$album['id']));?>">Delete</a>
 </td>
</tr>
<?php endforeach; ?>
</table>